
server:
  servlet:
    #application-display-name: lovely_trip
    context-path: /lovely_trip/api/v1

spring:
  application:
    name: lovelyTrip

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: victoriachang
    password: testDBVic
    hikari:
      maximum-pool-size: 10 # Maximum database connections in the pool
      minimum-idle: 2       # Minimum number of idle connections
      connection-timeout: 20000  # Maximum wait time for a connection (in ms)
      max-lifetime: 1800000
      idle-timeout: 30000
      auto-commit: false

  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect # Hibernate dialect for PostgreSQL
    hibernate:
      ddl-auto: update  # Controls how Hibernate manages schema (update, create, none)
    show-sql: true # Logs SQL statements for debugging
    properties:
      hibernate:
        format_sql: true #Formats SQL output for readability
        default_schema: lovely_trip
        #dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
